<?php

/**
 * BaseForumQuestions
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $text
 * @property integer $author_Id
 * @property integer $category_Id
 * @property string $title
 * @property ForumCategory $ForumCategory
 * @property ForumUsers $ForumUsers
 * @property Doctrine_Collection $ForumAnswer
 * 
 * @method string              getText()          Returns the current record's "text" value
 * @method integer             getAuthorId()      Returns the current record's "author_Id" value
 * @method integer             getCategoryId()    Returns the current record's "category_Id" value
 * @method string              getTitle()         Returns the current record's "title" value
 * @method ForumCategory       getForumCategory() Returns the current record's "ForumCategory" value
 * @method ForumUsers          getForumUsers()    Returns the current record's "ForumUsers" value
 * @method Doctrine_Collection getForumAnswer()   Returns the current record's "ForumAnswer" collection
 * @method ForumQuestions      setText()          Sets the current record's "text" value
 * @method ForumQuestions      setAuthorId()      Sets the current record's "author_Id" value
 * @method ForumQuestions      setCategoryId()    Sets the current record's "category_Id" value
 * @method ForumQuestions      setTitle()         Sets the current record's "title" value
 * @method ForumQuestions      setForumCategory() Sets the current record's "ForumCategory" value
 * @method ForumQuestions      setForumUsers()    Sets the current record's "ForumUsers" value
 * @method ForumQuestions      setForumAnswer()   Sets the current record's "ForumAnswer" collection
 * 
 * @package    ForumProject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumQuestions extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forum_questions');
        $this->hasColumn('text', 'string', 1000, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 1000,
             ));
        $this->hasColumn('author_Id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('category_Id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('title', 'string', 50, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 50,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_unicode_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('ForumCategory', array(
             'local' => 'category_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasOne('ForumUsers', array(
             'local' => 'author_Id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $this->hasMany('ForumAnswer', array(
             'local' => 'id',
             'foreign' => 'question_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}