<?php

/**
 * BaseForumCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property Doctrine_Collection $ForumQuestions
 * 
 * @method string              getName()           Returns the current record's "name" value
 * @method Doctrine_Collection getForumQuestions() Returns the current record's "ForumQuestions" collection
 * @method ForumCategory       setName()           Sets the current record's "name" value
 * @method ForumCategory       setForumQuestions() Sets the current record's "ForumQuestions" collection
 * 
 * @package    ForumProject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forum_category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));

        $this->option('charset', 'utf8');
        $this->option('collate', 'utf8_unicode_ci');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ForumQuestions', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}