<?php

/**
 * BaseForumUsers
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $username
 * @property string $password
 * @property Doctrine_Collection $ForumQuestions
 * 
 * @method string              getUsername()       Returns the current record's "username" value
 * @method string              getPassword()       Returns the current record's "password" value
 * @method Doctrine_Collection getForumQuestions() Returns the current record's "ForumQuestions" collection
 * @method ForumUsers          setUsername()       Sets the current record's "username" value
 * @method ForumUsers          setPassword()       Sets the current record's "password" value
 * @method ForumUsers          setForumQuestions() Sets the current record's "ForumQuestions" collection
 * 
 * @package    ForumProject
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseForumUsers extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('forum_users');
        $this->hasColumn('username', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 255,
             ));
        $this->hasColumn('password', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('ForumQuestions', array(
             'local' => 'id',
             'foreign' => 'author_Id'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}