<?php
// auto-generated by sfViewConfigHandler
// date: 2015/06/04 17:49:12
$response = $this->context->getResponse();


  $templateName = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_template', $this->actionName);
  $this->setTemplate($templateName.$this->viewName.$this->getExtension());



  if (null !== $layout = sfConfig::get('symfony.view.'.$this->moduleName.'_'.$this->actionName.'_layout'))
  {
    $this->setDecoratorTemplate(false === $layout ? false : $layout.$this->getExtension());
  }
  else if (null === $this->getDecoratorTemplate() && !$this->context->getRequest()->isXmlHttpRequest())
  {
    $this->setDecoratorTemplate('' == 'layout' ? false : 'layout'.$this->getExtension());
  }
  $response->addHttpMeta('content-type', 'text/html', false);

  $response->addStylesheet('main.css', '', array ());
  $response->addStylesheet('styles.css', '', array ());
  $response->addStylesheet('bootstrap.css', '', array ());
  $response->addJavascript('js.js', '', array ());
  $response->addJavascript('jquery-2.1.1.js', '', array ());
  $response->addJavascript('jquery.noty.packaged.min.js', '', array ());


