<?php

/**
 * ForumCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumCategory');
    }
}