<?php

/**
 * ForumQuestionsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumQuestionsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumQuestionsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumQuestions');
    }
}