<?php

/**
 * ForumUsersTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumUsersTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumUsersTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumUsers');
    }
}