<?php

/**
 * ForumAnswerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForumAnswerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForumAnswerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForumAnswer');
    }
}