# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/13-View

default:
  http_metas:
    content-type: text/html

  metas:
    #title:        symfony project
    #description:  symfony project
    #keywords:     symfony, project
    #language:     en
    #robots:       index, follow

  stylesheets:    [main.css,styles.css,bootstrap.css,bootstrap.css]

  javascripts:    [js.js,jquery-2.1.1.js,jquery.noty.packaged.min.js]

  has_layout:     true
  layout:         layout
