<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2015/06/04 15:52:33

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=ForumProject',
  'username' => 'root',
  'password' => '',
  'name' => 'doctrine',
)),);
